// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBxqqkJnoyHWiIW9rZzXzJHWnlY4BY-fK0',
//     appId: '1:627097907001:web:b44b26b45ea2c6858602e8',
//     messagingSenderId: '627097907001',
//     projectId: 'todotaskapp-756b2',
//     authDomain: 'todotaskapp-756b2.firebaseapp.com',
//     storageBucket: 'todotaskapp-756b2.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCg7i_8YNPCkSuZYQPZZXq7bDW18c2BFtA',
//     appId: '1:627097907001:android:30e94234350336fe8602e8',
//     messagingSenderId: '627097907001',
//     projectId: 'todotaskapp-756b2',
//     storageBucket: 'todotaskapp-756b2.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDkmSpmJwQrJjMtzROiYD7Hcey2vDqf6ig',
//     appId: '1:627097907001:ios:c575ffb3cb45e5b08602e8',
//     messagingSenderId: '627097907001',
//     projectId: 'todotaskapp-756b2',
//     storageBucket: 'todotaskapp-756b2.appspot.com',
//     iosBundleId: 'com.example.todoTaskApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDkmSpmJwQrJjMtzROiYD7Hcey2vDqf6ig',
//     appId: '1:627097907001:ios:c575ffb3cb45e5b08602e8',
//     messagingSenderId: '627097907001',
//     projectId: 'todotaskapp-756b2',
//     storageBucket: 'todotaskapp-756b2.appspot.com',
//     iosBundleId: 'com.example.todoTaskApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBxqqkJnoyHWiIW9rZzXzJHWnlY4BY-fK0',
//     appId: '1:627097907001:web:0cdddb89745759e28602e8',
//     messagingSenderId: '627097907001',
//     projectId: 'todotaskapp-756b2',
//     authDomain: 'todotaskapp-756b2.firebaseapp.com',
//     storageBucket: 'todotaskapp-756b2.appspot.com',
//   );
// }
